# Generated by Django 5.1.1 on 2024-09-16 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="manufactured_at",
            field=models.DateField(
                blank=True,
                help_text="Введите дату производства изменения",
                null=True,
                verbose_name="Дата производства изменения",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                help_text="Введите категорию продукта",
                max_length=50,
                verbose_name="Категория продукта",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.PositiveIntegerField(
                help_text="Введите цену продукта",
                max_length=50,
                verbose_name="цена продукта",
            ),
        ),
    ]
